t2solute_sections = [
    'TITLE', 'OPTIONS', 'CONSTRAINTS', 'READIO', 'WEIGHT_DIFFU', 'TOLERANCE', 'PRINTOUT', 'NODES',
    'PRIMARY_SPECIES', 'MINERALS', 'AQUEOUS_SPECIES', 'ADSORPTION_SPECIES',
    'EXCHANGE_SPECIES', 'CHEMICAL_ZONES', 'CHEMICAL_ZONES_TO_NODES']

t2chemical_sections = [
    'TITLE', 'PRIMARY_AQUEOUS', 'AQUEOUS_KINETICS', 'AQUEOUS_COMPLEXES', 'MINERALS', 'GASES', 'SURFACE_COMPLEXES',
    'DECAY_SPECIES', 'EXCHANGEABLE_CATIONS', 'IB_WATERS', 'MINERAL_ZONES',
    'IJ_GAS', 'PERM_PORO', 'SURFACE_ADSORPTION', 'LINEAR_EQUILIBRIUM', 'CATION_EXCHANGE']

t2chemical_read_sections = [
    'TITLE', 'PRIMARY AQUEOUS', 'AQUEOUS KINETICS', 'AQUEOUS COMPLEXES', 'MINERALS', 'GASES', 'SURFACE COMPLEXES',
    'DECAY_SPECIES', 'EXCHANGEABLE_CATIONS', 'Initial Boundary WATERS', 'MINERAL ZONES',
    'Initial Injection GAS', 'PERMeability Porosity', 'Surface Adsorption', 'LINEAR EQUILIBRIUM', 'CATION EXCHANGE']

t2bio_sections = [
    'SIMUL', 'ROCKS', 'MULTI', 'CHEMP', 'NCGAS', 'BIODG', 'SOLIDS', 'PARAM', 'MOMOP', 'START', 'NOVER', 'RPCAP',
    'LINEQ', 'SOLVR', 'TIMES', 'SELEC', 'DIFFU',
    'ELEME', 'CONNE', 'MESHM', 'GENER', 'SHORT', 'FOFT',
    'COFT', 'GOFT', 'INCON', 'INDOM']

t2react_sections = [	
    'SIMUL', 'ROCKS', 'PARAM', 'REACT', 'MOMOP', 'START', 'NOVER', 'RPCAP',	
    'LINEQ', 'SOLVR', 'MULTI', 'TIMES', 'SELEC', 'DIFFU',	
    'ELEME', 'CONNE', 'MESHM', 'GENER', 'SHORT', 'FOFT',	
    'COFT', 'GOFT', 'INCON', 'INDOM']